### ISSUE TITLE
Launching Enhancements

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#13]
Launching enhancements:
- user specified VPC
- true autoscaling

**Comment by vlj91** [comment]
Regarding user specified VPC/network creation if no network parameters offered - 

When playing previously I came across the issue that whilst completely okay to do, there is an issue with the cluster login node and its dependency. 

When creating a private network - the login node must depend on the `InternetGateway` resource, to ensure that the stack deletes cleanly and in the right order. With a user specified VPC - the dependency on the internet gateway cannot exist, as the resource does not exist as it was never created. 

I've looked, but cannot see an appropriate way of saying if the internet gateway resource doesn't exist then don't depend on it. 

The only appropriate method I can really see to fix this is to have two sets of cluster login node resource blocks: 
1. create login node and depend on internet gateway resource if private cluster network is created
2. create login node with no dependency as no network creation has taken place

It doesn't really present a problem but also isn't the cleanest method of doing it. What are your thoughts?

**Comment by sierra-tango-echo** [comment]
user specified VPC requirement discussed in #23

**Comment by sierra-tango-echo** [comment]
dropping the user specified VPC requirement from 2016.2, we'll see if anyone actually needs it and can't make do with custom non-marketplace cf templates

**Comment by vlj91** [comment]
This issue was moved to alces-software/flight-appliance-templates#19
