### ISSUE TITLE
Multiple Scheduler Support

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#15]
Multiple scheduler support
- Slurm
- Torque
- OpenLava

**Comment by mjtko** [comment]
Addressed in:

https://github.com/alces-software/clusterware-services/issues/17
https://github.com/alces-software/clusterware-services/issues/20
https://github.com/alces-software/clusterware-services/issues/18
https://github.com/alces-software/clusterware-services/issues/26

And:

https://github.com/alces-software/clusterware-handlers/issues/28
https://github.com/alces-software/clusterware-handlers/issues/27
https://github.com/alces-software/clusterware-handlers/issues/26
https://github.com/alces-software/clusterware-handlers/issues/39

**Comment by vlj91** [comment]
This is included in `2016.3`
