### ISSUE TITLE
Adjust AutoScaling policy times

### ISSUE THREAD

**Issue by vlj91** [alces-software/flight-aws-marketplace#22]
To ensure environments are not left with jobs queueing and no compute nodes available - the minimum capacity increase alarm/autoscaling policy time should be reduced to a much lower time (e.g. 5 minutes or so)

The other available alarms/policies should also be adjusted in order to not clash in time and both perform an action at the same time

**Comment by sierra-tango-echo** [comment]
simplified the autoscaling process in #28 so this should no longer be an issue
