### ISSUE TITLE
Public IP address in cloudformation console changes when login instance stopped/started

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#25]
@vlj91 reported:

Stopping/starting again
Works okay, but the public IP address displayed in the CloudFormation console will become incorrect once the instance shuts down; as the instance will pick up a new public IP when it starts back up

Obviously, need to either wait for cluster to have scaled down compute hosts or manually shut down compute nodes first

@stevenorledge
ip there is nothing we can do about that

We need to investigate further to try and find a workaround, or at least warn users in some way in a FAQ document on starting and stopping clusters once running

**Comment by vlj91** [comment]
This issue was moved to alces-software/flight-appliance-templates#13
