### ISSUE TITLE
Include new CloudWatch alarms

### ISSUE THREAD

**Issue by vlj91** [alces-software/flight-aws-marketplace#3]
New CloudWatch alarms for scheduler metrics: 

https://github.com/alces-software/imageware/issues/17
https://github.com/alces-software/imageware/issues/18
https://alces.slack.com/archives/imageware/p1459979486000099

**Comment by vlj91** [comment]
Re-opening to track additionally required alarms. From @mjtko:

> Send three metrics (initially):
> number of 2-core nodes required to fulfil slot-based queueing jobs and node-based queueing jobs
> number of 16-core nodes
> number of 36-core nodes
> For these metrics, set up alarms:
> If value >= 1 add 1 node
> If value >= 2 add 1 node
> If value >= 3 add 1 node
> If value >= 4 add 1 node
> If value >= 5 add 1 node
> If value >= 6 add 1 node
> If value >= 7 add 1 node
> If value >= 8 add 1 node
> If value >= 9 add 1 node
> If value >= 10 add 1 node
> If value >= 15 add 5 nodes
> If value >= 20 add 5 nodes
> If value >= 30 add 10 nodes
> If value >= 40 add 10 nodes
> If value >= 50 add 10 nodes
> If value >= 75 add 25 nodes
> If value >= 100 add 25 nodes

**Comment by sierra-tango-echo** [comment]
this isn't going to make 2016.2, we have limited scaling which will have to do - we need to revisit how this is done and give clusterware more control over how many nodes get added, what types and when, I don't think cloudwatch on the qw metric alone is clever enough to make informed decisions.

**Comment by vlj91** [comment]
This is covered by the new CloudWatch alarm/autoscaler which better calculates the number of nodes required to complete the number of queued jobs.
