### ISSUE TITLE
ASG templates not deleting properly

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#30]
When deleting a cf 8 node template thats not spun up all 8, I get on deletion:

Cancelled
Could not scale to desired capacity because all re...
2016 May 2 09:11:33 UTC+1
2016 May 2 09:11:33 UTC+1
Description:DescriptionCould not scale to desired capacity because all remaining instances are protected from scale-in.
Cause:CauseAt 2016-05-02T08:11:23Z a user request update of AutoScalingGroup constraints to min: 0, max: 0, desired: 0 changing the desired capacity from 2 to 0. At 2016-05-02T08:11:33Z group reached equilibrium.

**Comment by sierra-tango-echo** [comment]
further investigation of this suggests that it might be something to do with what clusterware is doing at shutdown or similar.
If i take the IAM role away from the login and compute instances, the cf deletes cleanly. Maybe on shutdown they are signalling to the deleting ASG that they need to do something? Need to understand what clusterware is doing, so need ure help @mjtko

**Comment by sierra-tango-echo** [comment]
I'm also seeing this during running, which is causing problems. I think its when we are shutting down instances around the same time we are asking for more.. Maybe we should not shutdown anything if there is stuff in the queue - it that even possible? 

Cancelled
Placing Spot instance request
2016 May 2 14:11:23 UTC+1
2016 May 2 14:12:22 UTC+1
Description:DescriptionPlacing Spot instance request. Status Reason: Spot instance request: sir-01trcele has been cancelled unexpectedly. User might have cancelled Spot instance request or Group size might have decreased while waiting for Spot instance request to be fulfilled.
Cause:CauseAt 2016-05-02T13:11:09Z a monitor alarm sfn2-CPUAlarmHigh-131YLX5F590CC in state ALARM triggered policy sfn2-ScaleUp-21VE6DIIXK3M changing the desired capacity from 1 to 2. At 2016-05-02T13:11:23Z a difference between desired and actual capacity changing the desired capacity, increasing the capacity from 1 to 2.

**Comment by sierra-tango-echo** [comment]
found a workaround which is to manually reduce the ASG desired to 0, then shuts down cleanly - still think it's related to clusterware|ASG conflicting somewhere though :(

**Comment by mjtko** [comment]
The Clusterware side of this all runs on the master node and behaves as follows:
1. When a node joins the cluster ring, mark it as protected from scale-in
2. Every 5 minutes:
   1. send job metrics to cloudwatch
   2. check if there are any nodes viable for scale-in:
      1. for all empty nodes, disable all queues
      2. check if any empty nodes are "exhausted" (i.e. within the last 7 minutes of an instance hour)
      3. for all empty nodes:
         1. if unexhausted enable all queues
         2. if exhausted, shoot the node: deprotect from scale-in, reduce autoscaling group capacity by 1, send event to tell node to halt

Sounds like instance protection is getting in the way somehow, perhaps due to some restriction of CF?

**Comment by mjtko** [comment]
The change in the `cluster-sge` handler above simplifies things as follows:

There is no longer a (1).

2(i)(a)(b) now does: if exhausted shoot the node if possible: terminate the instance using `terminate-instance-in-group` with `--should-decrement-desired-capacity`. (will fail if minimum would be breached).

**Comment by sierra-tango-echo** [comment]
tested, all now seems to behave :)
