### ISSUE TITLE
Offer more instance types, for compute and login nodes in the default templates

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#31]
Initially we wanted to keep this list small, on second thoughts theres good reasons to have a longer list of instance types - as long as the default for each template suggests a good choice, adding extra choice shouldn't be a problem at this stage.

**Comment by sierra-tango-echo** [comment]
[Flight_Compute_AWS_spot_instances - Sheet1.pdf](https://github.com/alces-software/flight-aws-marketplace/files/245181/Flight_Compute_AWS_spot_instances.-.Sheet1.pdf)

**Comment by wdm78** [comment]
Updated PDF - some of the high-memory instances were "R2" type that didn't support HVM on Linux

[Flight_Compute_AWS_spot_instances - Compute_SPOT.pdf](https://github.com/alces-software/flight-aws-marketplace/files/245684/Flight_Compute_AWS_spot_instances.-.Compute_SPOT.pdf)

**Comment by sierra-tango-echo** [comment]
implemented in 8,16,32,x templates.
