### ISSUE TITLE
ASG min nodes ignored by clusterware

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#32]
Clusterware shuts down nodes regardless of the min nodes set on ASG, ideally we need to not do this, because if we do the ASG just fires them back up again :)

**Comment by mjtko** [comment]
Due to changes in clusterware handler as above, this should no longer be an issue as `terminate-instance-in-group` will not allow the minimum to be breached.

**Comment by sierra-tango-echo** [comment]
tested, all now seems to behave :)
