### ISSUE TITLE
nodes shutdown, when not using the scheduler. 

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#34]
people not running jobs through the scheduler (this is the first think i believe some recent new users actually did) are gonna have problems with nodes being shutdown in a scaling cluster mid job. discuss.......

**Comment by sierra-tango-echo** [comment]
@mjtko thoughts?

**Comment by mjtko** [comment]
Argh, yeah, that will be a pain.

Maybe we could also look at 5-minute load average and if it's >1 (1.5? 2?) we avoid shooting the node.  Not an exact science though.

Or massive banner/warning at first login? "Disable autoscaling if you're not going to use the scheduler by running..."

Or banner on ssh to a node?

**Comment by sierra-tango-echo** [comment]
how would we currently "Disable autoscaling" in clusterware, is there a switch/command for that?

**Comment by mjtko** [comment]
No switch/command atm, "easy" way is to `rm -f /etc/cron.d/clusterware-cluster-sge-autoscaler`.

**Comment by sierra-tango-echo** [comment]
I think maybe a banner warning that it is enabled and a command to disable / check status of / automatic node shutdown

**Comment by mjtko** [comment]
As above commits, we now have a banner and a command to disable/enable/check status.
