### ISSUE TITLE
User/Commercial application mountpoint

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#37]
Investigate adding an /opt/apps and /opt/apps/etc/modules etc by default to flight compute to enable self install of commercial applications and home grown modulefiles.

**Comment by mjtko** [comment]
Flight Compute appliances now have an `/opt/apps` area for user (non-Gridware) applications.

`/opt/apps/etc/modules` is initialized with the `null` modulefile and added to the global modulespath. `/opt/apps` is exported via Clusterware NFS handling from the master node to all slave nodes.

This will undoubtedly need further enhancement in future, documented processes, etc. but serves as a starting point.
