### ISSUE TITLE
Configure swap memory on instances

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#46]
Linux memory management can perform badly when there is no swap memory configured. This enhancement request is to include configuration of a small amount of swap memory on compute and login node instances.

**Comment by sierra-tango-echo** [comment]
@wdm78 what did your investigations find other people are doing with regards to swap on instances that have no local disk?

**Comment by wdm78** [comment]
General unwritten rule seems to be:
- Anything based on EL6 seems to include swap
- Any AMIs based on EL7 or Ubuntu seem to not include swap

There are lots of recommendations that swapping on EBS is a terribly bad idea, so possibly we don't want to do this on AWS. I guess it would be useful to be able to have swap enabled, but this is lower priority than I first thought

**Comment by mjtko** [comment]
Seems like this would be a good idea on instances that have ephemeral/instance store available to them, but for others would be a bad plan.  Out of our current options, only `r3` and `g2` nodes have instance store; `c4` and `m4` types appear not to.

**Comment by vlj91** [comment]
This issue was moved to alces-software/flight-appliance-templates#18
