### ISSUE TITLE
Viewing storage configurations setup with alces storage command

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#47]
It would be useful to be able to see the names of storage configurations setup by users with the `alces storage configure` command.

**Comment by mjtko** [comment]
What’s the use case here? Users can see what they have set up by using `alces storage avail` — is this for admin use?

**Comment by wdm78** [comment]
I think I was getting confused about what `alces storage avail` displays - ideally, I'd like a way to see both what storage areas are setup, and what storage types are enabled. I think `alces storage avail` is doing the former, when I'd wrongly assumed it was doing the latter. This issue should probably be about how to list what storage back-ends are enabled (or available to be enabled).

**Comment by mjtko** [comment]
If you want to see what backends are available, you can do this:

```
[vagrant@login-2bf7dc3(el7cluster) ~]$ al sto avail --backends
[ ] base/dropbox
[*] base/posix
[*] base/s3
```

Do we need both in one view? Maybe it's a bit confusing to have both behaviours under one command?

**Comment by mjtko** [comment]
Perhaps `avail` for backends and `show` to show the configured storage areas?

**Comment by vlj91** [comment]
Moving to clusterware as it is more appropriate there

**Comment by vlj91** [comment]
This issue was moved to alces-software/clusterware#203
