### ISSUE TITLE
Notification support on Flight Compute

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#48]
Support notifications, of things such as
Cluster Status
Job Status

Initial methods of notification to support
AWS ses -> http://docs.aws.amazon.com/ses/latest/DeveloperGuide/postfix.html
AWS sns

Other methods to consider (maybe whitepapar)
Twitter
Slack

**Comment by vlj91** [comment]
This issue was moved to alces-software/flight-appliance-templates#14
