### ISSUE TITLE
Flight Compute needs a list of available applications

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#49]
We need an online list of applications available in Flight Compute to go with the product documentation. Ideally, the list would be generated automatically based on the currently available apps. Some sort of application grouping or filter by purpose or subject-matter type would also be useful (if quite subjective).

**Comment by sierra-tango-echo** [comment]
@wdm78 Can you give a manually created example of the sort of thing you suggest?

**Comment by wdm78** [comment]
Is was thinking something like this - https://drive.google.com/open?id=0Bz9WbfgfTa34OWJaUG94WXRWOUk; that's created using the group listed in the package metadata. This list was created using packages in the volatile repo, so possibly we'd want to separate based on repo too?

**Comment by vlj91** [comment]
This is now available here: https://github.com/alces-software/flight-appliance-docs/blob/master/docs/source/apps/gridware.rst
