### ISSUE TITLE
Launching on AWS m3 instance type generates an error

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#51]
Error message:

`Placing Spot instance request. Status Reason: Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type. Placing Spot instance request failed.`

**Comment by sierra-tango-echo** [comment]
r3.4xlarge works

**Comment by sierra-tango-echo** [comment]
c4.8xlarge ok
c4.xlarge ok
c4.4xlarge ok
c4.2xlarge ok
m4.4xlarge ok
m4.10xlarge ok
r3.8xlarge ok
r3.2xlarge ok
r3.xlarge ok

m3.2xlarge fail
m3.xlarge fail
