### ISSUE TITLE
Failed to launch Flight in AWS regions that don't support lambda

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#56]
Release version was 2016.2r2 - tested in Sydney region. Error was:
`17:03:21 UTC+0100     CREATE_FAILED     AWS::Lambda::Function     ClusterIdentityFunction     Resource is not supported in this region`

**Comment by mjtko** [comment]
See perfectly evil hack in 8befc832a374ffeb13273e6d0dd7cdb1251b5bae.

In summary it adds a map to show which regions have AWS Lambda available, and behaves as before in those regions.  In regions which are Lambda-retarded, the CFT now falls back to using the ID of the security group for the `token` and `uuid` fields.

**Comment by sierra-tango-echo** [comment]
Refs #61 we need to remove lambda completely from the aws templates :(
