### ISSUE TITLE
ASG fails to create when initial nodes > max nodes in x-node template

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#62]
you get...  Desired capacity:5 must be between the specified min size:1 and max size:4

**Comment by sierra-tango-echo** [comment]
not sure how we fix this one, because with both initial nodes and max nodes being dynamic means we can't validate it before the template is executed. Maybe we just need a workaround, currently all I can think of is not ask for an initial in the x-node template :(

**Comment by mjtko** [comment]
We could change the template so it does "if initial nodes > max nodes, use initial nodes as max nodes"?
