### ISSUE TITLE
Stop / Start Scaling Clusters

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#63]
When Autoscaling is enabled, its a long winded process to 'stop' the cluster and come back to it later. We need to provide functionality from flight compute to pause the autoscaling, shutdown the compute nodes then allow the user to 'stop' the login node. 

When resumed, the user should be able to resume the compute nodes, from the same state the ASG was at before the pause.

**Comment by vlj91** [comment]
This issue was moved to alces-software/flight-appliance-templates#9
