### ISSUE TITLE
Set smaller defaults for AWS MP CFN template

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#66]
Our AWS Marketplace page needs to show a link to the AWS price calculator based on the "default" settings for the template. At present, this is 32 nodes, which is big and makes Flight Compute look expensive to run. Please can we change the defaults in the template to:
- 4 x compute.small (c4.large) compute nodes
- on-demand nodes (not a good idea to default to spot)
- auto-scaling off
- medium sized login node (r3.2xlarge)
- 500GB of EBS (the current default)

This should provide reasonable performance for testing without being too expensive.

**Comment by sierra-tango-echo** [comment]
this is on the x template?

AS off and spot off is already the default ?

**Comment by wdm78** [comment]
Yes - in the X-node template we use for Marketplace. Please keep AS=off and spot=off as the defauilt
