### ISSUE TITLE
Compute node sizes listed in AWS CFN template might be difficult to understand

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#67]
I'm worried that we've simplified the compute node sizes too much in the CFN template - while it's useful to have "small/medium/large" descriptions, it's tricky to work out exactly how many cores/GB-of-RAM you'll get from the different options, especially if you've not used AWS much (which new users won't have). We could change our descriptions to the following, but then it's starting to get too complicated and difficult to read:

```
      "compute-2C-3GB.small-c4.large" 
      "compute-8C-15GB.medium-c4.2xlarge" 
      "compute-16C-30GB.large-c4.4xlarge"
      "compute-36C-60GB.dedicated-c4.8xlarge"
      "balanced-4C-16GB.small-m4.xlarge"
      "balanced-8C-32GB.medium-m4.2xlarge"
      "balanced-16C-64GB.large-m4.4xlarge"
      "balanced-40C-160GB.dedicated-m4.10xlarge"
      "memory-4C-30GB.small-r3.xlarge"
      "memory-8C-60GB.medium-r3.2xlarge"
      "memory-16C-120GB.large-r3.4xlarge"
      "memory-32C-240GB.dedicated-r3.8xlarge"
      "gpu.medium-g2.2xlarge"
      "gpu.dedicated-g2.8xlarge"
      "small-t2.large"
      "medium-r3.2xlarge"
      "large-c4.8xlarge"
```

Discuss :)

**Comment by sierra-tango-echo** [comment]
if they need that then yes the only option is in the name, only allowed . and -

could just put the link to the instance descriptions in the description text though?

**Comment by wdm78** [comment]
Okay - maybe that's a better idea; we can do a docs page that describes the instance types, and put a link to that on the marketplace page somewhere
