### ISSUE TITLE
Debug script for users to run that need support

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/flight-aws-marketplace#73]
We should consider writing a debug script that collects as much info as possible from a running Flight compute environment and tars it up to help with diagnosing problems. 

Things to think about
- logs
- network settings
- cloudinit data
- userdata
- instance metadata
- hosts files
- hostname -f / hostname -i results 
- disk sizes / space remaining
- installed packages

etc

**Comment by mjtko** [comment]
Associated to this, we could/should add the capability of adding an Alces Flight SSH public key to an existing/new account to allow Alces engineers the ability to perform a remote login and diagnosis of issues.

**Comment by vlj91** [comment]
This issue was moved to alces-software/flight-appliance-templates#6
