### ISSUE TITLE
Compute node disk size needs increasing for use with AMI default size

### ISSUE THREAD

**Issue by vlj91** [alces-software/flight-aws-marketplace#77]
If the AMI default size is above the specified compute node disk size, the creation of each compute node instance will fail: 

```
Placing Spot instance request. Status Reason: Volume of size 20GB is smaller than snapshot 'snap-fbf63316', expect size >= 32GB (400 response code). Spot instance request: sir-01hbax4p has failed.
```

**Comment by sierra-tango-echo** [comment]
I think 20GB by default for a compute node is fine, I've reduced the default size of the AMI to 16GB, hopefully this is a decent default now (i can install the biggest depot at least)

**Comment by sierra-tango-echo** [comment]
16GB version of 2016.r3 ami, rolled out to all regions from Alces Flight

AMI eu-west1: ami-b8c350cb
[ap-southeast-1]  AMI created: ami-8b62b3e8
[ap-southeast-2]  AMI created: ami-d20f21b1
[eu-central-1]  AMI created: ami-f77d9298
[ap-northeast-2]  AMI created: ami-47da1129
[ap-northeast-1]  AMI created: ami-bc29c5dd
[us-east-1]  AMI created: ami-df6c9eb2
[sa-east-1]  AMI created: ami-faa52e96
[us-west-1]  AMI created: ami-67daa107
[us-west-2]  AMI created: ami-945ba2f4
