### ISSUE TITLE
Cannot launch Flight AMI from Marketplace on G2 instances

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#79]
Manual launch of an AMI on a G2 instance fails with the message:

`Launch Failed
The instance configuration for this AWS Marketplace product is not supported. Please see http://aws.amazon.com/marketplace/pp?sku=3yptc3x57erijcq5ecih02efx for more information about supported instance types, regions, and operating systems.`

**Comment by wdm78** [comment]
Also due to the AMI restriction, launching a cluster with "g2" compute node instance types fails because the AMI will not start on the nodes. Note - the CFN template completes normally, as the auto-scaling group gets created; the error message that the AMI isn't supported on G2 instance types is logged for the scaling group, not the template (i.e. user gets a cluster login node but no compute nodes)

**Comment by mjtko** [comment]
This was fixed a while back.

(Please reopen if I’ve misunderstood!)
