### ISSUE TITLE
CFN template should document minimum 16GB size for LoginSystemDiskSize parameter

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#82]
Launching with LoginSystemDiskSize <16GB fails (as the AMI is 16GB) - we should note this limit in the CFN template help text, and product docs

**Comment by vlj91** [comment]
Setting `MinValue` on `LoginSystemDiskSize` would also be useful, and stop it from failing

**Comment by vlj91** [comment]
A minimum system disk size of 16GB is now required
